version: "3"
services:
  pg:
    image: mdillon/postgis:10
    container_name: 'breakdown-pg'
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_DB: 'test'
    networks:
      - database
volumes:
  pgdata:
networks:
  database:
    driver: bridge
