version: 0.2
phases:
  install:
    commands:
      # Install yarn natively https://yarnpkg.com/en/docs/install#linux-tab
      - sudo apt-get update && sudo apt-get install apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update && sudo apt-get install yarn
      # NPM token for Epsagon
      - npm config set '//registry.npmjs.org/:_authToken' '3325bbb0-195f-4c59-abeb-edf8a0755be7'
      - yarn
  build:
    commands:
      - yarn run web:prod
  post_build:
    commands:
      - aws s3 cp dist/ s3://$S3_BUCKET --recursive --acl public-read
artifacts:
  type: zip
  files:
    - node_modules/**/*
    - lib/**/*.js
    - $OUTPUT_TEMPLATE_FILE
